#dalarcont Software Development Services
#API REST for Universidad Mísera Administración y Académia
#2023

#Basic data for Sping framework
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:universidadfalsa}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:D4larcont#}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

#URL's service base
server.servlet.context-path=/api/ies
server.port=${PORT:8315}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

