package com.ies.ies_admin_academ.model.entities;

public final class IES_EmailTemplates {

    public static String IES_HTML_CSS(){
        return new StringBuilder()
                .append("<style>")
                .append(".uf_mail_default_template {")
                .append("	overflow: auto;")
                .append("	width: 100%;")
                .append("}")
                .append(".uf_mail_default_template table {")
                .append("	border: 1px solid #dededf;")
                .append("	height: 100%;")
                .append("	width: 100%;")
                .append("	table-layout: fixed;")
                .append("	border-collapse: collapse;")
                .append("	border-spacing: 1px;")
                .append("	text-align: center;")
                .append("	font-family: 'Trebuchet MS', Helvetica, sans-serif;")
                .append("}")
                .append(".uf_mail_default_template caption {")
                .append("	caption-side: top;")
                .append("	text-align: center;")
                .append("}")
                .append("")
                .append(".uf_mail_default_template th {")
                .append("	border: 1px solid #dededf;")
                .append("	background-color: #006bb3;")
                .append("	color: #ffffff;")
                .append("	padding: 5px;")
                .append("}")
                .append(".uf_mail_default_template td {")
                .append("	border: 1px solid #dededf;")
                .append("	background-color: #ffffff;")
                .append("	color: #000000;")
                .append("	padding: 5px;")
                .append("}")
                .append("td.issue_office {")
                .append("	font-size: 25px;")
                .append("}")
                .append("td.privacy {")
                .append("	font-size: 10px;")
                .append("}")
                .append("td.subject {")
                .append("	font-size: 18px;")
                .append("}")
                .append("td.content {")
                .append("	font-size: 14px;")
                .append("}")
                .append("</style>").toString();
    }

    public static String IES_WELCOME_NEW_USER(String[] msgContent){
        return new StringBuilder()
                .append(IES_HTML_CSS())
                .append("<div class='uf_mail_default_template' role='region' tabindex='0'>" )
                .append("<table>" )
                .append("<thead>" )
                .append("<tr>" )
                .append("<th>UF<br>Universidad Falsa</th>" )
                .append("</tr>" )
                .append("</thead>" )
                .append("<tbody>" )
                .append("<tr>" )
                .append("<td class='issue_office'>Oficina de Registro y Control</td>" )
                .append("</tr>" )
                .append("<tr>" )
                .append("<td class='subject'>")
                .append(msgContent[0])
                .append("</td>")
                .append("</tr>" )
                .append("<tr>" )
                .append("<td class='content'><br>Confirmamos que hemos realizado tu registro en nuestro sistema de información.<br>" )
                .append("A partir del recibo de esta comunicación ya te encuentras registrado en la Universidad Falsa.<br><br>" )
                .append("Confirmamos tus datos básicos: <br><br>" )
                .append("<b>Identificación: ")
                .append(msgContent[1])
                .append("</b><br>")
                .append("<b>Nombre de usuario: ")
                .append(msgContent[2])
                .append("</b><br>")
                .append("<b>Nombre completo: ")
                .append(msgContent[3])
                .append("</b> <br><br></td>")
                .append("</tr>" )
                .append("<tr>" )
                .append("<td class='privacy'>Este correo es informativo.<br>Por favor no responder<br>" )
                .append("Si usted no es el destinatario final de este mensaje por favor haga caso omiso de esta comunicación.<br>" )
                .append("Universidad Falsa<br>2024" )
                .append("</td>" )
                .append("</tr>" )
                .append("</tbody>" )
                .append("</table>" )
                .append("</div>")
                .toString();
    }
}
