package com.ies.ies_admin_academ.model.entities;

import java.io.Serializable;

public class uf_personas_estudiante extends uf_personas implements Serializable {

    private String FEC_PRIMER_MATRICULA;
    private String FEC_ULTIMA_MATRICULA;
    private int COD_ULTIMO_PROGRAMA_MATRICULADO;
    private String ESTADO_DISCIPLINARIO;
    private String ESTADO_ACADEMICO_GENERAL;
    private boolean PERMISO_ACCESO;
    private String FEC_ULTIMO_ACCESO;

    //Custom properties created by the original properties with its codes given
    private String NOM_ESTADO_DISCIPLINARIO;
    private String NOM_ESTADO_ACADEMICO_GENERAL;

    public uf_personas_estudiante() {
        super();
    }

    public uf_personas_estudiante(int PRSN_REG, String PRSN_FEC_REG, String PRSN_ID, String PRSN_NOM, String PRSN_APE, String PRSN_USUARIO, String PRSN_GEN, String PRSN_EMAIL_PERSONAL, String PRSN_EMAIL_LABORAL, String PRSN_ORIGEN_PAIS, String PRSN_ORIGEN_CIUDAD, String PRSN_RESIDE_PAIS, String PRSN_RESIDE_CIUDAD, String PRSN_ESCOLARIDAD, String PRSN_PKEY, String PRSN_RECOVERY_QUEST, String PRSN_RECOVERY_ANS, String PRSN_GEN_NOM, String PRSN_ORIGEN_PAIS_NOM, String PRSN_ORIGEN_RESIDE_NOM, String PRSN_ESCOLARIDAD_NOM, String FEC_PRIMER_MATRICULA, String FEC_ULTIMA_MATRICULA, int COD_ULTIMO_PROGRAMA_MATRICULADO, String ESTADO_DISCIPLINARIO, String ESTADO_ACADEMICO_GENERAL, boolean PERMISO_ACCESO, String FEC_ULTIMO_ACCESO, String NOM_ESTADO_DISCIPLINARIO, String NOM_ESTADO_ACADEMICO_GENERAL) {
        super(PRSN_REG, PRSN_FEC_REG, PRSN_ID, PRSN_NOM, PRSN_APE, PRSN_USUARIO, PRSN_GEN, PRSN_EMAIL_PERSONAL, PRSN_EMAIL_LABORAL, PRSN_ORIGEN_PAIS, PRSN_ORIGEN_CIUDAD, PRSN_RESIDE_PAIS, PRSN_RESIDE_CIUDAD, PRSN_ESCOLARIDAD, PRSN_PKEY, PRSN_RECOVERY_QUEST, PRSN_RECOVERY_ANS, PRSN_GEN_NOM, PRSN_ORIGEN_PAIS_NOM, PRSN_ORIGEN_RESIDE_NOM, PRSN_ESCOLARIDAD_NOM);
        this.FEC_PRIMER_MATRICULA = FEC_PRIMER_MATRICULA;
        this.FEC_ULTIMA_MATRICULA = FEC_ULTIMA_MATRICULA;
        this.COD_ULTIMO_PROGRAMA_MATRICULADO = COD_ULTIMO_PROGRAMA_MATRICULADO;
        this.ESTADO_DISCIPLINARIO = ESTADO_DISCIPLINARIO;
        this.ESTADO_ACADEMICO_GENERAL = ESTADO_ACADEMICO_GENERAL;
        this.PERMISO_ACCESO = PERMISO_ACCESO;
        this.FEC_ULTIMO_ACCESO = FEC_ULTIMO_ACCESO;
        this.NOM_ESTADO_DISCIPLINARIO = NOM_ESTADO_DISCIPLINARIO;
        this.NOM_ESTADO_ACADEMICO_GENERAL = NOM_ESTADO_ACADEMICO_GENERAL;
    }

    public String getFEC_PRIMER_MATRICULA() {
        return FEC_PRIMER_MATRICULA;
    }

    public void setFEC_PRIMER_MATRICULA(String FEC_PRIMER_MATRICULA) {
        this.FEC_PRIMER_MATRICULA = FEC_PRIMER_MATRICULA;
    }

    public String getFEC_ULTIMA_MATRICULA() {
        return FEC_ULTIMA_MATRICULA;
    }

    public void setFEC_ULTIMA_MATRICULA(String FEC_ULTIMA_MATRICULA) {
        this.FEC_ULTIMA_MATRICULA = FEC_ULTIMA_MATRICULA;
    }

    public int getCOD_ULTIMO_PROGRAMA_MATRICULADO() {
        return COD_ULTIMO_PROGRAMA_MATRICULADO;
    }

    public void setCOD_ULTIMO_PROGRAMA_MATRICULADO(int COD_ULTIMO_PROGRAMA_MATRICULADO) {
        this.COD_ULTIMO_PROGRAMA_MATRICULADO = COD_ULTIMO_PROGRAMA_MATRICULADO;
    }

    public String getESTADO_DISCIPLINARIO() {
        return ESTADO_DISCIPLINARIO;
    }

    public void setESTADO_DISCIPLINARIO(String ESTADO_DISCIPLINARIO) {
        this.ESTADO_DISCIPLINARIO = ESTADO_DISCIPLINARIO;
    }

    public String getESTADO_ACADEMICO_GENERAL() {
        return ESTADO_ACADEMICO_GENERAL;
    }

    public void setESTADO_ACADEMICO_GENERAL(String ESTADO_ACADEMICO_GENERAL) {
        this.ESTADO_ACADEMICO_GENERAL = ESTADO_ACADEMICO_GENERAL;
    }

    public boolean isPERMISO_ACCESO() {
        return PERMISO_ACCESO;
    }

    public void setPERMISO_ACCESO(boolean PERMISO_ACCESO) {
        this.PERMISO_ACCESO = PERMISO_ACCESO;
    }

    public String getFEC_ULTIMO_ACCESO() {
        return FEC_ULTIMO_ACCESO;
    }

    public void setFEC_ULTIMO_ACCESO(String FEC_ULTIMO_ACCESO) {
        this.FEC_ULTIMO_ACCESO = FEC_ULTIMO_ACCESO;
    }

    public String getNOM_ESTADO_DISCIPLINARIO() {
        return NOM_ESTADO_DISCIPLINARIO;
    }

    public void setNOM_ESTADO_DISCIPLINARIO(String NOM_ESTADO_DISCIPLINARIO) {
        this.NOM_ESTADO_DISCIPLINARIO = NOM_ESTADO_DISCIPLINARIO;
    }

    public String getNOM_ESTADO_ACADEMICO_GENERAL() {
        return NOM_ESTADO_ACADEMICO_GENERAL;
    }

    public void setNOM_ESTADO_ACADEMICO_GENERAL(String NOM_ESTADO_ACADEMICO_GENERAL) {
        this.NOM_ESTADO_ACADEMICO_GENERAL = NOM_ESTADO_ACADEMICO_GENERAL;
    }
}